### ISSUE TITLE
Is this work completed?

### ISSUE THREAD

**Issue by qiaodongxing** [christopher-evans/mvsnerf-implementation#1]
Thank you for your great work. It seems that this code has a much clearer structure than the official implementation. Is this work completed? How long will it take to complete

**Comment by christopher-evans** [comment]
Thanks for your message, I had not expected anyone to find this so quickly!

It is in progress at the moment, I have run the train/validate steps end to end with a single scene from DTU but there are still some issues I am debugging before running on a larger dataset.

This is a project I will be working on over the next few months, I will add a section in the README to say that it is still under development to make this clearer, and indicate which features are working as they are completed.
